# ──────────────────────────────────────────────
# Project   : Sure
# File      : CMakeLists.txt
# Author    : Emad Redwan
# Created   : 9/4/25
# License   : MIT
# ──────────────────────────────────────────────


add_library(Traits
    INTERFACE
    Arithmetic.hpp
    Base.hpp
    Common.hpp
    Comp.hpp
    Creation.hpp
    From.hpp
    Helpers.hpp
    Inc.hpp
    Iterator.hpp
    Primitives.hpp
)